name: Terraform Minikube Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Minikube
        run: |
          curl -Lo /tmp/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x /tmp/minikube
          sudo mv /tmp/minikube /usr/local/bin/minikube
          minikube config set driver docker

      - name: Start Minikube
        run: |
          minikube start

      - name: Install kubectl
        run: |
          curl -Lo /tmp/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x /tmp/kubectl
          sudo mv /tmp/kubectl /usr/local/bin/kubectl

      - name: Configure kubectl
        run: |
          minikube kubectl -- get po -A
